services:
  app:
    image: ${IMAGE_URL_PREFIX_APP}leetmail:main
    build:
      context: .
    volumes:
      - ./config.yml:/app/config.yml
    env_file: .env

  cron:
    image: ${IMAGE_URL_PREFIX_CRON}docker-curl-cron:master
    build:
      context: ./docker-curl-cron/
    env_file: .env
